Setpoint:
  ros__parameters:
    type: 0
    default:
      amplitude: 1.0
      frequency: 2.0
      offset: 0.0
    sinusoidal:
      amplitude: 1.0
      frequency: 1.0
      offset: 0.0
    square:
      amplitude: 1.0
      frequency: 5.0
      offset: 0.0
    sawtooth:
      amplitude: 0.5
      frequency: 2.0
      offset: 0.0
